[package]
name = "bfi_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bfi_lib = { path = "../bfi_lib" }
clap = { version = "4.5.17", features = ["derive"] }

[features]
full_extract = ["bfi_lib/full_extract"]  
