[package]
name = "bfi_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
pcap = "2.2"
byteorder = "1.5"
polars = { version = "0.42", features = ["parquet", "lazy"] }
thiserror = "1.0.63"
bilge = "0.2.0"
