[package]
name = "bfi_py_binding"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
numpy = "0.21"
bfi_lib = { path = "../bfi_lib" }

[lib]
name = "bfi_extract"
crate-type = ["cdylib"]
